#!/bin/bash
character=$1
if [ -z "$1" ]
then 
echo -e "Enter the type of desired calculation? \n  "
echo -e "1=First relaxation step"
echo -e "2=Second relaxation step with having CONTCAR"
echo -e "3=Last step (just getting energy and any other information)"
echo -n "?"
read character
else
structure="Deform01  Deform02  Deform03"
feshar=
if [ "$character" = "1" ]; then
    echo "You entered one."
for Pres in $structure
do
   cd $Pres
       feshar="`ls`"
       for Pressure in $feshar       
do
      mkdir $Pressure
      cd $Pressure

      cp ../../POTCAR  ./POTCAR
      cp ../../INCAR   ./INCAR
      cp ../../qsub.x  ./
      bsub < qsub.x  
     cd ..
   done
  cd ..
done
else
    if [ "$character" = "2" ]; then
        echo "You entered two."
variable=$(grep 'J' qsub.x | cut -c9-15)
var=$(bjobs |grep $variable)
if [ -z "$var" ]
then
for Pres in  $structure
do
   cd A$Pres
              for Pressure in $feshar
       do
       cd $Pressure
#------------for checking the convergence
final=$(grep F OSZICAR |tail -1|cut -c3-4)
echo "number"
if [ "$final"  == " 1" ];then
cd ..
continue
#fi
#----------------------------------------
#cd ..
#cd ..
else
       cp ../../qsub.x  ./
       cp ../../INCAR  ./INCAR
#       mv ./POSCAR ./POSCAR_old
       mv ./OUTCAR ./OUTCAR_old
       mv ./OSZICAR ./OSZICAR_old
#       cp ./CONTCAR ./POSCAR
       let "P=$Pressure*10"
       echo "PSTRESS = $P" >> ./INCAR
       bsub < qsub.x
fi
cd ..
done
cd ..
done
else
echo "$var"
echo "Calculations are not DONE yet! "
fi
   else
        if [ "$character" = "3" ]; then
            echo "You entered three."
for Pres in $structure
do     
pwd
   cd A$Pres
pwd
       for Pressure in $feshar 
       do
       cd $Pressure
pwd
#     a=$(grep "external pressure" ./OUTCAR|tail -n 1)
#     echo " "$Pressure", "$Pres" :  $a" >> ../../Energy.of.Different.composition
     b=$(grep "volume of cell" ./OUTCAR|tail -n 1|cut -c 21-30)
     kb=$(grep "in kB" ./OUTCAR|tail -n 1)
     echo "  "$kb" " >> ../../Energy.of.Different.composition    
     energy=$(grep 'F= ' ./OSZICAR |tail -n 1 | cut -c 8-23)
     echo " $Pres $Pressure  $energy  $b" >> ../../Energy.of.Different.composition
cd ..
done
cd ..
done
        else
            echo "You did not enter a number"
            echo "between 1 and 3."
       fi
    fi
fi
fi
