# Adapted from https://github.com/pandas-dev/pandas/blob/main/azure-pipelines.yml
trigger:
  branches:
    include:
    - master
    - 1.2.x
  paths:
    exclude:
    - 'doc/**'

pr:
  autoCancel: true
  branches:
    include:
    - master
    - 1.2.x

variables:
  PYTEST_WORKERS: auto
  PYTEST_TARGET:  FPTE
  PATTERN: "not slow and not high_memory and not db and not network and not single_cpu"
  FPTE_CI: 1

jobs:
# Mac and Linux use the same template
- template: .github/workflows/ci/posix.yml
  parameters:
    name: macOS
    vmImage: macOS-10.15


- job: py38_32bit
  pool:
    vmImage: ubuntu-18.04

  steps:
    # TODO: GH#44980 https://github.com/pypa/setuptools/issues/2941
    - script: |
        docker pull quay.io/pypa/manylinux2014_i686
        docker run -v $(pwd):/FPTE quay.io/pypa/manylinux2014_i686 \
        /bin/bash -xc "cd FPTE && \
        /opt/python/cp38-cp38/bin/python -m venv ~/virtualenvs/FPTE-dev && \
        . ~/virtualenvs/FPTE-dev/bin/activate && \
        python -m pip install --no-deps -U pip wheel 'setuptools<60.0.0' && \
        pip install cython numpy python-dateutil pytz pytest pytest-xdist hypothesis pytest-azurepipelines && \
        python setup.py build_ext -q -j2 && \
        python -m pip install --no-build-isolation -e . && \
        pytest -m 'not slow and not network and not clipboard' FPTE --junitxml=test-data.xml"
      displayName: 'Run 32-bit manylinux2014 Docker Build / Tests'
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test-*.xml'
        failTaskOnFailedTests: true
        testRunTitle: 'Publish test results for Python 3.8-32 bit full Linux'